---
title: "backpack"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sp)
library(sf)
library(viridis)
library(RColorBrewer)
library(readxl)
library(gstat)
library(tidyverse)
library(mapview)
library(lwgeom)
library(classInt)
library(grid)
library(raster)
library(lubridate)
library(ggplot2)
library("ggmap")
```

```{r}
# Read and extract data from two waypoint files and then combine the data frames into one file. 

# We then select columns, filter rows, rename column/field names, ... easily and intuitively using the `dplyr` package.

data_1 <- read.csv("data/wp_01.wpt", sep=",", skip=4)
data_1 <- dplyr::select(data_1, c(2,3,4))
colnames(data_1) <- c("dose", "lat", "lon")
data_1 <- mutate(data_1, source = "wp_01")

data_2 <- read.csv("data/wp_02.wpt", sep=",", skip=4)
data_2 <- dplyr::select(data_2, c(2,3,4))
colnames(data_2) <- c("dose", "lat", "lon")
data_2 <- mutate(data_2, source = "wp_02")

data <- rbind(data_1, data_2)

# Converting doses from uGy/h to nGy/h
data <- mutate(data, dose = dose*1000)
```

* Quick look at first rows:

```{r}
head(data)
```

* Quick look at last rows:

```{r}
tail(data)
```

* Getting Summary Statistics :

```{r}
summary(data)
```

* How many points are collected per `source` (name of data collector)?

```{r}
data %>% 
  count(source)
```

```{r warning = FALSE, message = FALSE, fig.width = 7, fig.height = 4}
#  1. first ggplot's layer: ggplot(data, mapping = aes(x = dose)) specifying data
#     and aesthetics mapping (here the dose variable to x positioning)
#  2. second layer: geom_histogram(fill = "steelblue") specifying we want an 
#     histogram
#  3. last layer: facet_grid(source ~  .) specifying we want to breakdown the 
#     histogram by source (here name of data collector)

ggplot(data, mapping = aes(x = dose)) +
  geom_histogram(fill = "steelblue") +
  facet_grid(source ~  .)
```

```{r warning = FALSE, message = FALSE}
#  1. Base layer: pass data and map "lon" and "lat" variables respectively to
#     x and y aesthetics
#  2. add a "point" layer and map "dose" variable to the color aesthetic with
#     alpha (opacity) to 0.8 (0 is transparent and 1 is opaque) and points size
#  3. specify a color palette. "direction = -1" reverses the color order
#  4. specity a map projection. Look at ?coord_map in RStudio console for
#     further details. Map projections will be covered more carefully later on.
#
ggplot(data, mapping = aes(x = lon, y = lat)) +
  geom_point(aes(color = dose), alpha = .8, size = 2) +
  scale_color_viridis(direction = -1) +
  coord_quickmap()
```

```{r}
# If the data set was huge (e.g. 20,000+ measurements) we could sample 10,000 points from available data 
# subset <- data[sample(1:nrow(data), 10000),]

# Convert our data/subset to a "sf" package "compatible" object
# with associated crs (Coordinate Reference System - further details later on)
# and specifying "lon" and "lat" columns in original dataset
# subset <- st_as_sf(subset, coords = c("lon", "lat"), crs = 4326)
 data_sf <- st_as_sf(data, coords = c("lon", "lat"), crs = 4326)

# Create an interactive map with "mapview" funtion from the "mapview" package
#   - zcol: variable to be colour encoded
#   - map.types: base layer (here Esri satellite imagery)
#   - legend: do we want a legend or not

mapview(data_sf, zcol = "dose", map.types = "Esri.WorldImagery", legend = TRUE)
```

```{r}
# Where source is different from "wp_02"
no_wp_02 <- data %>% 
  filter(source != "wp_02")
```

```{r}
rg_lon <- range(no_wp_02$lon)
rg_lat <- range(no_wp_02$lat)

data_site_only <- data %>% 
  filter(lon > rg_lon[1] & lon < rg_lon[2] & lat > rg_lat[1] & lat < rg_lat[2])
```

```{r warning = FALSE, message = FALSE}
ggplot(data_site_only, mapping = aes(x = lon, y = lat)) +
  geom_point(aes(color = dose), alpha = .6, size = 1) +
  scale_color_viridis(direction = -1) +
  coord_quickmap()
```

```{r}
#Set your API Key
register_google(key = "AIzaSyBTnAyGePvGO94QIVH4LZTRMVkrt2SFWxs")
```

```{r warning = FALSE, message = FALSE}
# First download a satellite basemap - here a Google one. NOte that the coordinates indicated are mean values of the data_site_only file.
library("ggmap")
register_google(key = "AIzaSyBTnAyGePvGO94QIVH4LZTRMVkrt2SFWxs")
brd_map <- get_map(location = c(16.50858772, 47.97499538), maptype = "satellite", zoom = 18)

#qmap(Argentina, zoom = 18, maptype = "hybrid")
library(sf)
countries <- st_read("presentations/data/world_countries_wgs84.shp")
plot(st_geometry(countries_3857))
```
plot(st_geometry(countries_3857))

```{r warning = FALSE, message = FALSE}
# Overlay data based on lat and lon attributes
# Access ?ggmap documentation for details on extent option (not really important actually)
ggmap(brd_map, extent = "device") +
  geom_point(aes(x = lon, y = lat), colour = "red", alpha = 0.3, size = 1.5, data = data_site_only)
```

```{r warning = FALSE, message = FALSE}
ggmap(brd_map, extent = "device") + 
  geom_density2d(data = data_site_only, aes(x = lon, y = lat), size = 0.3, colour = "white") + 
  stat_density2d(data = data_site_only, aes(x = lon, y = lat, fill = ..level.., alpha = ..level..), 
                 size = 0.01, bins = 16, geom = "polygon") + scale_fill_gradient(low = "green", high = "red") +
  scale_alpha(range = c(0, 0.3), guide = FALSE) +
  guides(fill=FALSE)
```

```{r}
ggmap(brd_map, extent = "device") +
  geom_point(aes(x = lon, y = lat), colour = "red", alpha = 1, size = 1.5, data = data_site_only[data_site_only$dose > 150,])
```

```{r}
# Convert dataframe to an "sf" compatible object
no_wp_02_sf <- st_as_sf(no_wp_02, coords = c("lon", "lat"), crs = 4326)
```

```{r}
no_wp_02_sf

# Quick plot
#   - "st_geometry(no_wp_02_sf)" specifies we only want to map the geometry. 
#   - Run "plot(no_wp_02_sf)" instead in RStudio console what happens?
plot(st_geometry(no_wp_02_sf))
```

```{r}
# - Each point is a "feature". 
# - "st_convex_hull" accept features as argument.
# - If you execute "st_convex_hull(no_wp_02_sf)"", you will get convex hulls around each 
#   individual feature (hereindividual points actually). This is not what we want.
# - By taking the "union" we group all available features to a unique one (multipoint feature)

site_perimeter <- st_convex_hull(st_union(no_wp_02_sf))
plot(site_perimeter)
```

```{r}
# Returns the area as name suggests
st_area(site_perimeter)
```

```{r}
st_length(site_perimeter)
```

```{r message = FALSE}
# Convert first our data to sf object
data <- st_as_sf(data, coords = c("lon", "lat"), crs = 4326)

# Computes the intersection
data_site_only <- st_intersection(data, site_perimeter)

plot(st_geometry(data_site_only))
```

```{r}
# Transform to UTM
data_utm <- st_transform(data_site_only, crs = 32633)
```

```{r}
# Bounding box
bbox_utm <- st_bbox(data_utm)

print("Delta X max (m)")
print(unname(bbox_utm[3] - bbox_utm[1]))
print("Delta Y max (m)")
print(unname(bbox_utm[4] - bbox_utm[2]))
```

```{r}
max_pts <- data_utm[data_utm$dose == max(data_utm$dose),]$geometry

data_utm <- data_utm %>% 
  mutate(distance = st_distance(geometry, max_pts))
```

```{r}
# Convert to Spatial class
data_sp <- as(data_utm, Class = "Spatial")
head(data_sp)
```

```{r}
hist(data_sp$dose)
```

```{r}
# Names of default coordinates name
coordnames(data_sp)

# Let's rename it for the sake of simplicity
coordnames(data_sp) <- c("x", "y")
```

```{r}
# List the pairs of points with same coordinates
head(zerodist(data_sp))
```

```{r}
data_sp <- data_sp[-zerodist(data_sp)[,1],] 
```

```{r}
hscat(dose ~ 1, data_sp, seq(1,10,1))
```

```{r}
dose_vgm <- variogram(dose ~ 1, data_sp, cloud = TRUE)
plot(dose_vgm)
```

```{r}
# - "dose ~ 1": single constant regressor leading to a spatially constant mean coefficient
#               Try "dose ~ x + y" (using x and y coordinates as regressor to 
#               potentially detrend our data). Is there any difference?
# - cloud = FALSE: Variogram cloud or sample variogram (FALSE)
# - boundaries: distance values of interest. In our case we provide two sequences from fine
#               resolution at short distance to coarse one at long distance
#
# Change the parameters to see differences (Warning: in the situation where you set cloud = TRUE, 
# take a subsample of the data otherwise it might take a lot of time)

#dose_vgm <- variogram(dose ~ 1, data_sp, cloud = FALSE, boundaries = c(seq(2,20,2), seq(21, 120, 10)))
dose_vgm <- variogram(dose ~ 1, data_sp, cloud = FALSE, 
                      boundaries = seq(2,20,1))

plot(dose_vgm)
```

```{r}
# Eyeball the variogram and estimate the initial parameters
nugget <- 400
psill <- 600 # Partial sill
range <- 10

# To see models available, execute "vgm()" in RStudio console: Nug, Exp, ...
# They are "canonical" class of functions to be fitted. 
# "kappa" parametrizes some models: for instance a Matern model with 
# kappa = 0.5 is the exponential model. In our case, we ask to find this parameter
# automatically.
# Finding the right function, parameters is more an "art" than a science. So try and interpret ...
v_model <- fit.variogram(dose_vgm, model = vgm(
    model = "Sph",
    nugget = nugget,
    psill = psill,
    range = range,
    fit.kappa = TRUE
) )

plot(dose_vgm, model = v_model)
```

```{r}
print(v_model)
```

```{r}
# First in the right projection
site_perimeter_utm <- st_transform(site_perimeter, crs = 32633)
# Then to sp compatible type
site_perimeter_sp <- as(site_perimeter_utm, Class = "Spatial")
```

```{r}
plot(site_perimeter_sp); points(data_sp)
```

```{r}
bbox_site <- bbox(site_perimeter_sp)
bbox_site
```

```{r}
# The first parameter is the bottom left corner
resolution <- 2
size_x <- as.integer((bbox_site[1,2] - bbox_site[1,1]) / resolution)
size_y <- as.integer((bbox_site[2,2] - bbox_site[2,1]) / resolution)
grid <- GridTopology(c(612526, 5314554), c(resolution, resolution), c(size_x, size_y))

# Create points with the same coordinate system as the boundary
gridpoints <- SpatialPoints(grid, proj4string = CRS(projection(site_perimeter_sp)))
plot(gridpoints)
```

```{r}
cropped_gridpoints <- crop(gridpoints, site_perimeter_sp)
plot(cropped_gridpoints)
```

```{r}
# Convert to SpatialPixels
spgrid <- SpatialPixels(cropped_gridpoints)
coordnames(spgrid) <- c("x", "y")
plot(spgrid)
```

```{r}
# We pass:
#   - the value to predict
#   - the dataset
#   - the output data
#   - our model from variogram
#   - we want to use max 100 surrounded points (would be computationally demanding otherwise)
dose_grid <- krige(dose ~ 1, data_sp, newdata = spgrid, model = v_model, nmax = 100)
```

```{r}
spplot(dose_grid, zcol = "var1.pred")
```

```{r}
spplot(dose_grid, zcol = "var1.var")
```

```{r}
threshold <- 150
dose_grid$pDose <- 1 - pnorm(threshold, mean = dose_grid$var1.pred, sd = sqrt(dose_grid$var1.var))
```

```{r}
spplot(dose_grid, zcol = "pDose")
```

```{r fig.width = 7, fig.height = 8}
display.brewer.all()
```

```{r}
# Choosing a colour palette
my.palette <- brewer.pal(n = 7, name = "YlGnBu")
```

```{r}
# Applying the new colour palette to our map
spplot(dose_grid, zcol = "var1.pred", col.regions = my.palette, cuts = 6, col = "transparent")
```

```{r}
# Discretizing using equal length intervals
breaks <- classIntervals(dose_grid$var1.pred, n = 6, style = "equal", intervalClosure = "right")

# Rounding and converting breaks to string ()
breaks.legend = sapply(breaks$brks, function(x) as.character(floor(x)))

# Applying the color palette and discretization
spplot(dose_grid, zcol = "var1.pred", col.regions = my.palette, cuts = 6, col = "transparent", at = breaks$brks, colorkey = list("labels" = breaks.legend, title = "test"))

# To manually add a colour key label
grid.text("Dose Rate (nGy/h)", x=unit(0.92, "npc"), 
          y=unit(0.50, "npc"), rot=-90,
          gp = gpar(fontsize = 10, fontface = "bold"))
```

```{r}
geocode(c("White House", "Uluru"))
```

```{r warning = FALSE, message = FALSE}
assess_breaks <- function(data, breaks) {
  ggplot() +
  geom_histogram(aes(data), fill = "steelblue") +
  geom_vline(xintercept = breaks, colour = "red")
}
```

```{r warning = FALSE, message = FALSE, fig.width = 7, fig.height = 4}

# Assessing kmeans discretization/binning
# Experiment several "style" discretization methods
breaks <- classIntervals(dose_grid$var1.pred, n = 6, style = "kmeans", intervalClosure = "right")

assess_breaks(dose_grid$var1.pred, breaks$brks)
```

```{r}
# idp: is the inverse distance weighting power (the vicinity of points to be considered).
#      Experiment several values and see how smooth or sharp your map becomes.
idw.out <- idw(dose ~1, data_sp, spgrid, idp = 2.5)
```

```{r}
spplot(idw.out, zcol = "var1.pred")
```

```{r}
idw.out.raster <- raster(idw.out)
mapview(idw.out.raster, alpha.regions = 0.5, legend = TRUE, map.types = "Esri.WorldImagery")
```


